const data = [
  {
    id: "house1",
    title: "House 1",
    price: 750,
    location: "New York",
    image: "https://picsum.photos/200/300",
    description: "This is a house",
    moveInDate: "02-22-2023",
    type: 3,
    feat: {
      bed: 2,
      bath: 2,
      area: "5x6.5",
    },
    featured: true,
  },
  {
    id: "house2",
    title: "House 2",
    price: 1000,
    location: "London",
    image: "https://picsum.photos/200/300",
    description: "This is a house",
    moveInDate: "02-19-2023",
    type: 3,
    feat: {
      bed: 4,
      bath: 1,
      area: "6x8",
    },
    featured: true,
  },
  {
    id: "bungalow1",
    title: "Bungalow 1",
    price: 2000,
    location: "New Delhi",
    image: "https://picsum.photos/200/300",
    description: "This is a Bungalow",
    moveInDate: "02-19-2023",
    type: 2,
    feat: {
      bed: 3,
      bath: 1,
      area: "4x7",
    },
    featured: true,
  },
  {
    id: "house3",
    title: "House 3",
    price: 950,
    location: "New York",
    image: "https://picsum.photos/200/300",
    description: "This is a house",
    moveInDate: "02-20-2023",
    type: 3,
    feat: {
      bed: 2,
      bath: 2,
      area: "4x6.5",
    },
    featured: true,
  },
  {
    id: "house4",
    title: "House 4",
    price: 1195,
    location: "London",
    image: "https://picsum.photos/200/300",
    description: "This is a house",
    moveInDate: "02-19-2023",
    type: 3,
    feat: {
      bed: 2,
      bath: 1,
      area: "3x4",
    },
    featured: true,
  },
  {
    id: "bungalow2",
    title: "Bungalow 2",
    price: 800,
    location: "New Delhi",
    image: "https://picsum.photos/200/300",
    description: "This is a Bungalow",
    moveInDate: "02-19-2023",
    type: 2,
    feat: {
      bed: 2,
      bath: 2,
      area: "5x7.5",
    },
  },
  {
    id: "apartment1",
    title: "Apartment 1",
    price: 1600,
    location: "New Delhi",
    image: "https://picsum.photos/200/300",
    description: "This is an Apartment",
    type: 1,
    feat: {
      bed: 2,
      bath: 2,
      area: "5x8",
    },
  },
  {
    id: "apartment2",
    title: "Apartment 2",
    price: 1300,
    location: "London",
    image: "https://picsum.photos/200/300",
    description: "This is an Apartment",
    type: 1,
    feat: {
      bed: 3,
      bath: 1,
      area: "6x6",
    },
  },
  {
    id: "bungalow3",
    title: "Bungalow 3",
    price: 1800,
    location: "New Delhi",
    image: "https://picsum.photos/200/300",
    description: "This is a Bungalow",
    moveInDate: "02-19-2023",
    type: 2,
    feat: {
      bed: 4,
      bath: 2,
      area: "5x7.5",
    },
  },
  {
    id: "apartment3",
    title: "Apartment 3",
    price: 1400,
    location: "New Delhi",
    image: "https://picsum.photos/200/300",
    description: "This is an Apartment",
    type: 1,
    feat: {
      bed: 2,
      bath: 1,
      area: "5x5",
    },
  },
];
export default data;
